name: Deploy para o Netlify

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Deploy no Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          # Pasta onde está o index.html ('.' indica a raiz)
          publish-dir: '.'
          # Secrets cadastrados no GitHub
          netliFy-account-id: nfp_BRh8GhCqvvN7yExKC3cNhNi9WBVy52Eed814
          netlify-auth-token: 9c0b75aa-7b67-41bd-8f27-a020eebdc2ba
          # Cria um deploy de preview para Pull Requests e oficial na branch principal
          deploy-to-require-alias: true
          production-deploy: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
          enable-commit-comment: true
